In [1]:
import numpy as np

In [2]:
#create-from lists
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)



[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [3]:
#create
arr1=np.zeros((2,3),dtype="int64") #prefil
print(arr1,arr1.shape)

arr2=np.ones((3,))
print(arr2,arr2.shape)

arr3=np.full((3,4),50)
print(arr3,arr3.shape)

arr4=np.eye(3)
print(arr4,arr4.shape)

arr5=np.arange(0,12,2)
print(arr5,arr5.shape)

arr6=np.linspace(1,100,4)
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1.] (3,)
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [4]:
#array properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
#type casting
float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [5]:
#operation on arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened=arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [6]:
arr=np.array([1,2,3,4,5])#1d
print(arr[0])
arr2=np.array([[1,2,3],[4,5,6]]) #2D
print(arr2[1][0])

1
4


In [7]:
#fancy indexing
arr=np.array([1,2,3,4,5])
idx=[1,3,4]
print(arr[idx])

[2 4 5]


In [8]:
#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>4])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[5]
[2 4]
[1 3 5]


In [9]:
#slicing
arr=np.array([1,2,3,4,5])
print(arr[1:3])
print(arr[::2])

[2 3]
[1 3 5]


In [10]:
#copy vs view
nums=[1,2,3,4,5]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

arr=np.array([1,2,3,4,5])
sub_array=arr[1:3].copy()   #.copy() for copying the view of sliced array
print(sub_array)
sub_array[0]=200

print(sub_array)
print(arr)




[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[1 2 3 4 5]


In [11]:
#data types
arr=np.array([1,2,3,4,5])
print(arr.dtype)
arr1=np.array([1,2,3,4,5.1])
print(arr1.dtype)
arr2=np.array([1,2,3,4,5.1,"prime"])
print(arr2.dtype)
arr3=np.array([1,2,3,4,5.1,3+4j])
print(arr3.dtype)
arr4=np.array([1,{2,3},4,5.1,3+4j,"prime"])
print(arr4.dtype)

int64
float64
<U32
complex128
object


In [12]:
#multi dimensional array
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
#for vertical sum=axis0
sum_of_columns=np.sum(arr2D,axis=0)
print(sum_of_columns)
#for horizontal sum=axis1
sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)
#slicing-for row(0,1) and column(1)
print(arr2D[0:2,1:2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [13]:
#3D ARRAY---->2 x 3 x 2 [two 3 x 2 array]
arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12 ]]])
print(arr3D,arr3D.shape)
#indexing--. give number presend at that index
print(arr3D[1,1,0])
print(arr3D[0,1,0])
#slicing---> first row of both layer
print(arr3D[:,0,:])
#slicing---> first column of both layer
print(arr3D[:,:,0])
#manupulation
arr3D[:,:,1]=99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
3
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[ 1 99]
  [ 3 99]
  [ 5 99]]

 [[ 7 99]
  [ 9 99]
  [11 99]]]


In [14]:
#vectorization
arr=np.array([1,2,3,4,5])
arr2=np.array([1,2,7,0,5])
print(arr ** 2)
print(arr+9)
print(arr+arr2)

[ 1  4  9 16 25]
[10 11 12 13 14]
[ 2  4 10  4 10]


In [15]:
#broadcasting
arr=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr+5)
print(arr2)
print(arr+arr2)

[ 6  7  8  9 10]
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [16]:
#vector normalization
arr=np.array([[1,2],[3,4]])
mean=(np.mean(arr))
std=(np.std(arr))
normalized_arr=(arr-mean)/std
print(normalized_arr)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [17]:
#MATHEMATICAL FXN:
#aggregation fxn
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [18]:
#power fnx
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1  16  81 256 625]


In [19]:
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [20]:
#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [21]:
print(np.unique(arr))

[1 2 3 4 5]
